# Generated by Django 4.0.6 on 2022-08-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phoneno',
            field=models.IntegerField(blank=True, default='0000000000', null=True),
        ),
    ]
