# Generated by Django 4.0.6 on 2022-09-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_account_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phoneno',
            field=models.IntegerField(default='9999999999'),
        ),
    ]
