# Generated by Django 4.0.6 on 2022-10-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='Others', max_length=200)),
                ('thumbnail_img', models.ImageField(upload_to='events')),
                ('show', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=800)),
                ('ans', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('opportunity', 'opportunity'), ('resources', 'resources'), ('none', 'none')], default='none', max_length=50, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=11, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('Front-End', 'Front-End'), ('Back-End', 'Back-End'), ('Others', 'Others')], default='none', max_length=200)),
                ('category', models.CharField(default='Others', max_length=200)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, choices=[('\\_@Cache\\doc-resourses.png', 'doc_resource'), ('\\_@Cache\x0bideo-resourses.png', 'vedio_resource'), ('\\_@Cache\\winged-sword_38006.png', 'none')], null=True, upload_to='icon')),
                ('show', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_img', models.ImageField(upload_to='team')),
                ('position', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
                ('lnkdin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('insta_url', models.URLField(blank=True, max_length=500, null=True)),
                ('tweet_url', models.URLField(blank=True, max_length=500, null=True)),
                ('fb_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
