# Generated by Django 4.0.6 on 2022-08-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_img', models.ImageField(upload_to='media/team')),
                ('position', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=50, verbose_name='hello')),
                ('lnkdin_url', models.URLField(max_length=500)),
                ('insta_url', models.URLField(max_length=500)),
                ('tweet_url', models.URLField(max_length=500)),
                ('fb_url', models.URLField(max_length=500)),
            ],
        ),
    ]
