# Generated by Django 4.0.6 on 2022-08-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='desc',
            field=models.CharField(max_length=50),
        ),
    ]
