# Generated by Django 4.0.6 on 2022-09-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icon'),
        ),
        migrations.AddField(
            model_name='resourses',
            name='subject',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('Front-End', 'Front-End'), ('Back-End', 'Back-End')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='resourses',
            name='category',
            field=models.CharField(default='Others', max_length=200),
        ),
        migrations.AlterField(
            model_name='resourses',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
