# Generated by Django 4.0.6 on 2022-09-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resourses_image_resourses_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourses',
            name='image',
            field=models.ImageField(blank=True, choices=[('doc', '_@Cache\\doc-resourses.png'), ('vedio', '_@Cache\\doc-resourses.png')], null=True, upload_to='icon'),
        ),
    ]
