# Generated by Django 4.0.6 on 2022-10-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_rename_events_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Opportunity', 'Opportunity'), ('Internship', 'Internship'), ('none', 'none')], default='Others', max_length=200),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('Opportunity', 'Opportunity'), ('Internship', 'Internship'), ('none', 'none')], default='none', max_length=50, verbose_name='Category'),
        ),
    ]
