# Generated by Django 4.0.6 on 2022-08-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_team_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=11, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
