# Generated by Django 4.0.6 on 2022-09-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resourses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourses',
            name='image',
            field=models.ImageField(blank=True, choices=[('_@Cache\\doc-resourses.png', 'doc'), ('_@Cache\x0bideo-resourses.png', 'vedio')], null=True, upload_to='icon'),
        ),
    ]
