# Generated by Django 4.0.6 on 2022-08-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='resourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000)),
                ('show', models.BooleanField()),
            ],
        ),
    ]
