# Generated by Django 4.0.6 on 2022-09-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_resourses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourses',
            name='image',
            field=models.ImageField(blank=True, choices=[('media\\_@Cache\\doc-resourses.png', 'doc_resource'), ('media\\_@Cache\x0bideo-resourses.png', 'vedio_resource'), ('media\\_@Cache\\winged-sword_38006.png', 'none')], null=True, upload_to='icon'),
        ),
        migrations.AlterField(
            model_name='resourses',
            name='subject',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('Front-End', 'Front-End'), ('Back-End', 'Back-End'), ('Others', 'Others')], default='none', max_length=200),
        ),
    ]
